=== sooyeoung/bit/web01/WebContent/step02/address.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT address (person*)>
<!ELEMENT person (name+, age?, (home|mobile))>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT home (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>

<!ATTLIST person
  no ID #REQUIRED
  coutry CDATA #IMPLIED
  lang (kor|eng|jp|ch) "kor"
>

=== sooyeoung/bit/web01/WebContent/step02/test02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
<!DOCTYPE address SYSTEM "address.dtd">
-->
<!DOCTYPE address PUBLIC "-//BIT//bit address//en" "address.dtd">
<address>
  <person no="P001">
    <name>홍길동</name>
    <name>홍좌진</name>
    <home>031-1111-1111</home>
  </person>
  
  <person no="P002">
    <name>임꺽정</name>
    <age>30</age>
    <mobile>010-2222-2222</mobile>
  </person>
  
  <person no='P003' coutry="korea" lang="kor" >
    <name>장보고</name>
    <home>02-1111-2222</home>
  </person>
  
  
</address>
